eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://192.168.230.133:8761/eureka/
spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost/unit02
    password: ps123456
    username: root
server:
  port: 8882
